-- generated by csdl-to-sql for target hana from metadata.csdl.xml

create sequence "MbtEpmDemoService_xs_data_metrics_id_seq" start with 1 increment by 1 no cache;

create column table "MbtEpmDemoService_xs_data_metrics"
(
    "id" bigint not null,
    "start" timestamp not null,
    "period" decimal(20,6) not null,
    "process" nvarchar(100) not null,
    "tenant" nvarchar(200) null,
    "provider" nvarchar(100) not null,
    "component" nvarchar(200) not null,
    "metric" nvarchar(100) not null,
    "unit" nvarchar(50) not null,
    "count" bigint null,
    "sum" bigint null,
    "average" decimal(25,2) null,
    "minimum" bigint null,
    "maximum" bigint null,
    primary key ("id")
);

create sequence "MbtEpmDemoService_BusinessPartnerSet_id_seq" start with 1 increment by 1 no cache;

create column table "MbtEpmDemoService_BusinessPartnerSet"
(
    "Address_AddressType" nvarchar(2) not null,
    "Address_Building" nvarchar(10) not null,
    "Address_City" nvarchar(40) not null,
    "Address_Country" nvarchar(3) not null,
    "Address_PostalCode" nvarchar(10) not null,
    "Address_Street" nvarchar(60) not null,
    "BusinessPartnerID" bigint not null,
    "BusinessPartnerRole" nvarchar(3) not null,
    "CompanyName" nvarchar(80) not null,
    "FaxNumber" nvarchar(30) not null,
    "LegalForm" nvarchar(10) not null,
    "PhoneNumber" nvarchar(30) not null,
    "row_version" bigint not null,
    primary key ("BusinessPartnerID")
);

create row table "MbtEpmDemoService_xs_repeatability_log"
(
    "CreationTime" timestamp not null,
    "ResponseStatus" smallint not null,
    "ClientID" varbinary(100) not null,
    "RequestID" varbinary(100) not null,
    "ContentID" varbinary(100) not null,
    "ResponseHeaders" nvarchar(1000) not null,
    "ResponseData1" varbinary(2000) null,
    "ResponseData2" blob null,
    primary key ("RequestID", "ContentID")
);

create index "MbtEpmDemoService_xs_repeatability_log_client_id_index" on "MbtEpmDemoService_xs_repeatability_log" ("ClientID");

create index "MbtEpmDemoService_xs_repeatability_log_creation_time_index" on "MbtEpmDemoService_xs_repeatability_log" ("CreationTime");

create sequence "MbtEpmDemoService_SalesOrderSet_id_seq" start with 1 increment by 1 no cache;

create column table "MbtEpmDemoService_SalesOrderSet"
(
    "BillingStatus" nvarchar(1) null,
    "BillingStatusDescription" nvarchar(60) null,
    "BusinessPartnerID" bigint not null,
    "ChangedAt" timestamp null,
    "CreatedAt" timestamp null,
    "CurrencyCode" nvarchar(5) null,
    "CustomerID" nvarchar(10) not null,
    "CustomerName" nvarchar(80) null,
    "DeliveryStatus" nvarchar(1) null,
    "DeliveryStatusDescription" nvarchar(60) null,
    "GrossAmount" decimal(16,3) null,
    "LifecycleStatus" nvarchar(1) null,
    "LifecycleStatusDescription" nvarchar(60) null,
    "NetAmount" decimal(16,3) null,
    "Note" nvarchar(255) null,
    "NoteLanguage" nvarchar(2) null,
    "SalesOrderID" bigint not null,
    "TaxAmount" decimal(16,3) null,
    "row_version" bigint not null,
    primary key ("SalesOrderID")
);

create index "MbtEpmDemoService_SalesOrderSet_rc_ToBusinessPartner" on "MbtEpmDemoService_SalesOrderSet" ("BusinessPartnerID");
